#!/usr/bin/env python3
import sys
import argparse
import os
import pkg_resources
sys.path.append('../')
sys.path.append('./')
from socru.SocruCreate import SocruCreate

version = ''
try:
	version = pkg_resources.get_distribution("socru").version
except pkg_resources.DistributionNotFound:
	version = 'x.y.z'

parser = argparse.ArgumentParser(
    description = '''
    Create genome arrangement type scheme.  Please cite our paper, "Socru: Typing of genome level order and orientation in bacteria", 
    Andrew J Page, Gemma Langridge, 
    bioRxiv 543702; (2019) doi: https://doi.org/10.1101/543702''',
    usage = 'socru_create [options] output_directory assembly.fasta', 
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)

parser.add_argument('output_directory', help='Output directory', type=str)
parser.add_argument('input_file', help='Input FASTA file (optionally gzipped)', type=str)


parser.add_argument('--max_bases_from_ends', '-m', help='Only look at this number of bases from start and end of fragment', type=int)
parser.add_argument('--threads','-t',  help='No. of threads to use', type=int, default=1)
parser.add_argument('--fragment_order', '-f',  help='Order of fragments, you may need to change this, example 1-2-3-4-5-6-7', type=str)
parser.add_argument('--dnaa_fasta',  '-d', help='Location of dnaA FASTA file, defaults to bundled', type=str)
parser.add_argument('--dif_fasta',  '-d', help='Location of dif FASTA file, defaults to bundled', type=str)

parser.add_argument('--debug', action='store_true', help='Turn on debugging', default = False)
parser.add_argument('--verbose', '-v', action='store_true', help='Turn on verbose output', default = False)

parser.add_argument('--version', action='version', version=str(version))

options = parser.parse_args()

g = SocruCreate(options)
g.run()
