#!/usr/bin/env python3
"""
Command-line utility to create a new Socru species database from a reference genome.

This script generates a custom database for a new species by analyzing a reference genome
assembly. It identifies rRNA operons, extracts inter-operon fragments, and creates the
necessary database files (FASTA sequences, BLAST database, and profile information) needed
for subsequent genome typing with Socru.

The created database can then be used with the main 'socru' command to type other genomes
of the same species.
"""

import sys
import argparse
import os
from importlib.metadata import version as get_version
# Add parent and current directories to path for module imports
sys.path.append('../')
sys.path.append('./')
from socru.SocruCreate import SocruCreate

# Set up command-line argument parser with citation information
parser = argparse.ArgumentParser(
    description = '''
    Create genome arrangement type scheme.  Please cite our paper, "Socru: Typing of genome level order and orientation in bacteria", 
    Andrew J Page, Gemma Langridge, 
    bioRxiv 543702; (2019) doi: https://doi.org/10.1101/543702''',
    usage = 'socru_create [options] output_directory assembly.fasta', 
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)

# Positional arguments - required inputs
parser.add_argument('output_directory', help='Output directory', type=str)
parser.add_argument('input_file', help='Input FASTA file (optionally gzipped)', type=str)

# Database creation options - control how the database is built
parser.add_argument('--max_bases_from_ends', '-m', help='Only look at this number of bases from start and end of fragment', type=int)
parser.add_argument('--threads','-t',  help='No. of threads to use', type=int, default=1)
parser.add_argument('--fragment_order', '-f',  help='Order of fragments, you may need to change this, example 1-2-3-4-5-6-7', type=str)
parser.add_argument('--dnaa_fasta',  '-d', help='Location of dnaA FASTA file, defaults to bundled', type=str)
parser.add_argument('--dif_fasta',  '-e', help='Location of dif FASTA file, defaults to bundled', type=str)

# Debugging and information options
parser.add_argument('--debug', action='store_true', help='Turn on debugging', default = False)
parser.add_argument('--verbose', '-v', action='store_true', help='Turn on verbose output', default = False)

parser.add_argument('--version', action='version', version='%(prog)s ' + get_version('socru'))

# Parse command-line arguments
options = parser.parse_args()

# Create the new species database
try:
    g = SocruCreate(options)
    g.run()
except (FileNotFoundError, FileExistsError, ValueError) as e:
    print(str(e), file=sys.stderr)
    sys.exit(1)
