#!/usr/bin/env python3
import sys
import argparse
import os
import pkg_resources
sys.path.append('../')
sys.path.append('./')
from socru.SocruUpdateProfile import SocruUpdateProfile

version = ''
try:
	version = pkg_resources.get_distribution("socru").version
except pkg_resources.DistributionNotFound:
	version = 'x.y.z'

parser = argparse.ArgumentParser(
	description = 'Admin utility to take the novel GS results and update the profile for the database',
	usage = 'socru_update_profile [options]',
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
	
parser.add_argument('socru_output_filename',  help='Socru output file', type=str )
parser.add_argument('profile_filename', help="profile.txt from database", type=str)
parser.add_argument('--output_file', '-o',  help='Output filename', type=str, default = 'updated_profile.txt')

parser.add_argument('--debug', action='store_true', help='Turn on debugging', default = False)
parser.add_argument('--verbose', '-v', action='store_true', help='Turn on verbose output', default = False)
parser.add_argument('--version', action='version', version=str(version))

options = parser.parse_args()

g = SocruUpdateProfile(options)
g.run()
