#!/usr/bin/env python3
import sys
import argparse
import os
import pkg_resources
sys.path.append('../')
sys.path.append('./')
from socru.SocruShrinkDatabase import SocruShrinkDatabase

version = ''
try:
	version = pkg_resources.get_distribution("socru").version
except pkg_resources.DistributionNotFound:
	version = 'x.y.z'

parser = argparse.ArgumentParser(
	description = 'Admin utility take a database and blast results and create a new shrunk database',
	usage = 'socru_shrink_database [options]',
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
	
	
parser.add_argument('blast_results',  help='Blast results file from running socru -b xxx against multiple assemblies', type=str )
parser.add_argument('input_database',  help='Directory containing database to shrink', type=str )
parser.add_argument('output_database', help="Output directory for new database, it must not already exist", type=str)
parser.add_argument('--min_fragment_size', help="Minimum fragment size in bases", type=int, default = 100000)

parser.add_argument('--debug', action='store_true', help='Turn on debugging', default = False)
parser.add_argument('--verbose', '-v', action='store_true', help='Turn on verbose output', default = False)
parser.add_argument('--version', action='version', version=str(version))

options = parser.parse_args()

g = SocruShrinkDatabase(options)
print(g.run())
