#!/usr/bin/env python3
import sys
import argparse
import os
import pkg_resources
sys.path.append('../')
sys.path.append('./')
from socru.SocruRebuildProfile import SocruRebuildProfile

version = ''
try:
	version = pkg_resources.get_distribution("socru").version
except pkg_resources.DistributionNotFound:
	version = 'x.y.z'

parser = argparse.ArgumentParser(
	description = 'Admin utility which will take in an existing profile and rebuild it',
	usage = 'socru_rebuild_profile [options]',
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)

parser.add_argument('profile_filename', help="profile.txt from database", type=str)
parser.add_argument('--output_file', '-o',  help='Output filename', type=str, default = 'updated_profile.txt')
parser.add_argument('--prefix', '-p',  help='Prefix', type=str, default = 'GS')

parser.add_argument('--debug', action='store_true', help='Turn on debugging', default = False)
parser.add_argument('--verbose', '-v', action='store_true', help='Turn on verbose output', default = False)
parser.add_argument('--version', action='version', version=str(version))

options = parser.parse_args()

g = SocruRebuildProfile(options)
g.run()


